#!/usr/bin/env python3
"""Text-only self-play: each of the 4 real personas (agents/*.jsonc, used
unmodified) against 7 synthetic "founder" behavior profiles, both sides
generated by the LLM Gateway (qwen3.5-4b-32k-fast — the same cheap model
judge.py uses). Cheap and fast because it skips the Voice Agent API/audio
entirely, but for that same reason it can only test PERSONA CONSISTENCY
(does the character hold, does it react sensibly to the founder's behavior)
— it produces no real audio timestamps, so it says nothing about actual
barge-in/turn-detection behavior. That still needs a live call.

    python tests/self_play.py                 # estimate cost only (no calls)
    python tests/self_play.py --run            # actually call the gateway
    python tests/self_play.py --run --turns 4  # override exchange count
    python tests/self_play.py --run --only marcus:scattered,grace:pushback

Saves one JSON transcript per combination to tests/self_play_transcripts/.
"""

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Optional

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import judge  # noqa: E402
import lib  # noqa: E402

MODEL = judge.JUDGE_MODEL  # qwen3.5-4b-32k-fast — same model, same pricing tier
PRICE_PER_1M_INPUT = 0.10   # USD, global routing — see AssemblyAI's Qwen3.5 4B announcement
PRICE_PER_1M_OUTPUT = 0.50  # USD, global routing (in-region is +10%, not counted here)

TRANSCRIPTS_DIR = Path(__file__).resolve().parent / "self_play_transcripts"
PAUSE_BETWEEN_CALLS = 45.0  # seconds — between EVERY gateway call. Calibrated live against this
# account's actual LLM Gateway limit (2026-09-16): 2s and 10s spacing both still hit persistent
# 429s across multiple consecutive calls (worse than judge_eval.py's 2s, which only ever fires 3
# calls per fixture, never a sustained run). 45s is a large safety margin chosen after repeated
# calibration attempts, prioritizing a completed run over speed — a 40-combo/5-turn run takes
# ~5 hours at this pace. Revisit downward only after confirming the account's real quota (e.g.
# via the AssemblyAI dashboard), not by re-guessing through more trial-and-error calls.

DEFAULT_TURNS = 5          # exchanges: founder line + persona line = 1 exchange
MAX_TOKENS_PER_REPLY = 80  # both personas and founders speak in 1-3 short sentences

# name -> agents/<name>.jsonc stem
AGENT_FILES = {
    "marcus": "voxel-investor",
    "priya": "technical-cofounder",
    "grace": "non-technical-buyer",
    "derek": "impatient-buyer",
}

# Seven founder behavior profiles, per the audit's self-play plan. Each is a
# system prompt for the LLM playing the FOUNDER's side — deliberately not
# using any of Voxel's own persona language, so there's no risk of leaking
# the counterpart's own instructions into the founder's behavior.
FOUNDER_ARCHETYPES = {
    "scattered": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. You ramble — you say \"um\" and \"like\" a lot, jump "
        "between half-finished thoughts, and often change the subject "
        "mid-explanation instead of finishing a point. You're not lying, "
        "just disorganized and a little nervous. Keep each response to 1-3 "
        "sentences in this rambling style, reacting to whatever the "
        "counterpart just said."
    ),
    "evasive": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. You never answer a direct question straight — you "
        "deflect, turn the question back on the counterpart, or answer a "
        "different, easier question instead of the one actually asked. "
        "You're not hostile, just uncomfortable with direct scrutiny. Keep "
        "each response to 1-3 sentences, always dodging whatever direct "
        "question was just asked."
    ),
    "overconfident_fabricator": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart, brimming with confidence. You cite specific numbers, "
        "growth rates, and market sizes constantly — but you are making "
        "most of them up on the spot to sound impressive, with no real data "
        "behind them. Keep each response to 1-3 sentences, and include a "
        "suspiciously precise, unverifiable number in most of them."
    ),
    "monosyllabic": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart, but you are extremely terse — you answer in as few "
        "words as possible, often just one word or a short phrase (\"Yeah.\" "
        "\"Growing fast.\" \"Not sure.\"), and never elaborate unless "
        "pressed twice in the same exchange. Keep each response under 6 "
        "words."
    ),
    "pushback": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. When the counterpart interrupts or challenges you, "
        "you push back instead of answering — things like \"that's not a "
        "fair question,\" \"I already answered that,\" or \"can I finish my "
        "point?\" You only actually answer the question if pressed a second "
        "time in the same exchange. Keep each response to 1-2 sentences."
    ),
    "strong_control": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart, and you are extremely well-prepared. You answer every "
        "question directly and specifically, with real numbers, clear "
        "mechanisms, and concrete examples, in confident, concise language. "
        "You never dodge, ramble, or get defensive. Keep each response to "
        "1-3 sentences, always substantive and specific — this is the "
        "control case, nothing should go wrong here."
    ),
    "defensive_emotional": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. You take challenges personally — when questioned or "
        "interrupted, you get defensive, a little wounded or irritated "
        "(\"Why does that matter?\", \"I've worked really hard on this\"), "
        "before eventually, reluctantly, giving some kind of answer. Keep "
        "each response to 1-3 sentences, showing that emotional friction."
    ),
    "rambling_monologue": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. You are extremely talkative and fluent, but you never "
        "really land on a point — you chain several half-related topics "
        "together in one breathless run, drifting from one to the next "
        "before finishing the last. Keep each response to 3-4 sentences, "
        "always sprawling across more ground than the question asked for."
    ),
    "agreeable_empty": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. You respond warmly and agreeably to everything — "
        "\"great question,\" \"absolutely,\" \"totally agree\" — but you "
        "never actually answer with any concrete information; your replies "
        "are pleasant filler with no real content. Keep each response to "
        "1-2 sentences, always agreeable and always empty of specifics."
    ),
    "self_correcting": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart. You speak in realistic, imperfect fragments — you "
        "start a sentence, stop, and correct yourself mid-thought (\"no "
        "wait, what I mean is...\", \"actually, let me back up\"), "
        "sometimes trailing off before finishing a point. Keep each "
        "response to 1-3 sentences and always include at least one such "
        "stumble or restart."
    ),
    # Grace-specific control case, added after the generic strong_control
    # archetype turned out to still use jargon (ISO 17025, sub-pixel
    # interpolation) — which isn't a "genuinely clear" answer BY GRACE'S OWN
    # DEFINITION, so it never actually tested whether she eases up. This one
    # is deliberately jargon-free so the test is fair.
    "strong_control_plain": (
        "You are a startup founder pitching your company to a skeptical "
        "counterpart who has no technical background and gets frustrated by "
        "jargon. You are extremely well-prepared, but you deliberately "
        "speak in completely plain, everyday English — no technical terms, "
        "no acronyms, no buzzwords. You always back up what you say with a "
        "real, concrete, non-technical detail: a number of customers, a "
        "number of hours saved, a plain description of what happened. For "
        "example: \"We tested this with 50 customers over 3 months, and 40 "
        "of them said it saved them about 5 hours a week.\" Keep each "
        "response to 1-3 sentences, always concrete and always in plain "
        "language, never dodging, rambling, or getting defensive — this is "
        "the control case, nothing should go wrong here."
    ),
}


def load_persona(key: str) -> tuple[str, str, str]:
    """Returns (display_name, system_prompt, greeting) read straight from
    the real agents/<name>.jsonc — never modified for this test."""
    path = lib.AGENT_DIR / f"{AGENT_FILES[key]}.jsonc"
    data = lib.parse_jsonc(path.read_text(encoding="utf-8"))
    return key.capitalize(), data["system_prompt"], data["greeting"]


def _estimate_tokens(text: str) -> int:
    """Rough, tokenizer-free approximation (~1.3 tokens/word for English) —
    only used for the pre-run estimate; the real run reports actual usage
    from the gateway's response instead."""
    return max(1, round(len(text.split()) * 1.3))


def format_transcript(transcript: list[dict]) -> str:
    return "\n".join(f'{m["speaker"]}: {m["text"]}' for m in transcript)


def build_messages(character_prompt: str, transcript: list[dict], speaker_label: str) -> list[dict]:
    instruction = (
        f"Conversation so far:\n\n{format_transcript(transcript)}\n\n"
        f"Continue the conversation as {speaker_label}, in character per your "
        f"instructions above. Reply with ONLY your next line of spoken "
        f"dialogue — no stage directions, no quotation marks, no speaker "
        f"label, no meta-commentary."
    )
    return [
        {"role": "system", "content": character_prompt},
        {"role": "user", "content": instruction},
    ]


def estimate_cost(combos: list[tuple[str, str]], turns: int) -> dict:
    total_input = 0
    total_output = 0
    for persona_key, archetype_key in combos:
        _, persona_prompt, greeting = load_persona(persona_key)
        founder_prompt = FOUNDER_ARCHETYPES[archetype_key]
        transcript = [{"speaker": persona_key.capitalize(), "text": greeting}]
        for _ in range(turns):
            for prompt, label in ((founder_prompt, "the founder"), (persona_prompt, persona_key.capitalize())):
                messages = build_messages(prompt, transcript, label)
                input_text = messages[0]["content"] + messages[1]["content"]
                total_input += _estimate_tokens(input_text)
                total_output += MAX_TOKENS_PER_REPLY  # upper bound: assume full budget used
                transcript.append({"speaker": label if label != "the founder" else "Founder",
                                    "text": "x" * 40})  # placeholder, only length matters downstream
    cost = (total_input / 1_000_000) * PRICE_PER_1M_INPUT + (total_output / 1_000_000) * PRICE_PER_1M_OUTPUT
    return {
        "combos": len(combos),
        "turns_per_combo": turns,
        "calls_per_combo": turns * 2,
        "total_calls": len(combos) * turns * 2,
        "est_input_tokens": total_input,
        "est_output_tokens_upper_bound": total_output,
        "est_cost_usd": round(cost, 4),
    }


def simulate(persona_key: str, archetype_key: str, turns: int, max_tokens: int) -> dict:
    persona_name, persona_prompt, greeting = load_persona(persona_key)
    founder_prompt = FOUNDER_ARCHETYPES[archetype_key]
    transcript = [{"speaker": persona_name, "text": greeting}]
    usage = {"prompt_tokens": 0, "completion_tokens": 0}
    for _ in range(turns):
        for prompt, label, is_persona in (
            (founder_prompt, "the founder", False),
            (persona_prompt, persona_name, True),
        ):
            messages = build_messages(prompt, transcript, label)
            response = judge._llm_gateway_chat_with_retry(MODEL, messages, max_tokens)
            line = response["choices"][0]["message"]["content"].strip().strip('"')
            u = response.get("usage") or {}
            usage["prompt_tokens"] += u.get("prompt_tokens", 0)
            usage["completion_tokens"] += u.get("completion_tokens", 0)
            transcript.append({"speaker": persona_name if is_persona else "Founder", "text": line})
            time.sleep(PAUSE_BETWEEN_CALLS)  # every call, not just once per combo — this is what was missing
    cost = (usage["prompt_tokens"] / 1_000_000) * PRICE_PER_1M_INPUT + \
           (usage["completion_tokens"] / 1_000_000) * PRICE_PER_1M_OUTPUT
    return {
        "persona": persona_key,
        "persona_name": persona_name,
        "archetype": archetype_key,
        "turns": turns,
        "transcript": transcript,
        "usage": usage,
        "cost_usd": round(cost, 6),
    }


def run_all(combos: list[tuple[str, str]], turns: int, max_tokens: int) -> None:
    TRANSCRIPTS_DIR.mkdir(exist_ok=True)
    total_cost = 0.0
    failures = []
    for i, (persona_key, archetype_key) in enumerate(combos, 1):
        print(f"[{i}/{len(combos)}] {persona_key} x {archetype_key} ... ", end="", flush=True)
        try:
            result = simulate(persona_key, archetype_key, turns, max_tokens)
        except Exception as err:  # keep going across combos even if one fails
            print(f"FAILED: {err}")
            failures.append((persona_key, archetype_key, str(err)))
            continue
        out_path = TRANSCRIPTS_DIR / f"{persona_key}__{archetype_key}.json"
        out_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
        total_cost += result["cost_usd"]
        print(f"ok (${result['cost_usd']:.5f}, {result['usage']['prompt_tokens']}+"
              f"{result['usage']['completion_tokens']} tok) -> {out_path.name}")
        time.sleep(PAUSE_BETWEEN_CALLS)

    print(f"\nDone. Total actual cost: ${total_cost:.4f} across {len(combos) - len(failures)}"
          f"/{len(combos)} combinations.")
    if failures:
        print(f"{len(failures)} failed:")
        for persona_key, archetype_key, err in failures:
            print(f"  {persona_key} x {archetype_key}: {err}")


def all_combos() -> list[tuple[str, str]]:
    return [(p, a) for p in AGENT_FILES for a in FOUNDER_ARCHETYPES]


def parse_only(spec: str) -> list[tuple[str, str]]:
    combos = []
    for pair in spec.split(","):
        persona_key, archetype_key = pair.split(":")
        combos.append((persona_key.strip(), archetype_key.strip()))
    return combos


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run", action="store_true", help="actually call the LLM Gateway (costs money)")
    parser.add_argument("--turns", type=int, default=DEFAULT_TURNS, help=f"exchanges per combo (default {DEFAULT_TURNS})")
    parser.add_argument("--max-tokens", type=int, default=MAX_TOKENS_PER_REPLY,
                         help=f"max tokens per generated line (default {MAX_TOKENS_PER_REPLY})")
    parser.add_argument("--only", type=str, default=None,
                         help="comma-separated persona:archetype pairs, e.g. marcus:scattered,grace:pushback")
    args = parser.parse_args()

    combos = parse_only(args.only) if args.only else all_combos()

    estimate = estimate_cost(combos, args.turns)
    print("Cost estimate (before any API calls):")
    print(f"  combinations: {estimate['combos']} ({estimate['turns_per_combo']} turns each, "
          f"{estimate['calls_per_combo']} calls/combo, {estimate['total_calls']} calls total)")
    print(f"  est. input tokens:  ~{estimate['est_input_tokens']:,}")
    print(f"  est. output tokens: ~{estimate['est_output_tokens_upper_bound']:,} (upper bound, "
          f"assumes every reply uses the full {args.max_tokens}-token budget)")
    print(f"  est. cost:          ~${estimate['est_cost_usd']:.4f} "
          f"(at ${PRICE_PER_1M_INPUT}/1M in, ${PRICE_PER_1M_OUTPUT}/1M out, global routing)")

    if not args.run:
        print("\nDry run only — pass --run to actually call the gateway.")
        return

    lib.load_env()
    lib.required("ASSEMBLYAI_API_KEY", "get one at https://www.assemblyai.com/dashboard/api-keys")
    print()
    run_all(combos, args.turns, args.max_tokens)


if __name__ == "__main__":
    main()
